### ISSUE TITLE
Choose external JavaScript library

### ISSUE THREAD

**Issue by segarciat** [ddjefferson/PetShelf#1]

**Comment by segarciat** [comment]
Some ideas:

- [Algolia Places](https://www.algolia.com/): Address auto completion, display maps, help with HTML forms.
- [Animation on Scroll](https://michalsnik.github.io/aos/) or [fullPage.js](https://github.com/alvarotrigo/fullPage.js/): we may be able to use to create a tutorial/guide for first-time pet owners.
- [Chart.js](https://www.chartjs.org/): We can display information related to pet adoption perhaps, or something else

**Comment by sinne24** [comment]
line 219 in index.html, js library is used.
